#spring:
#  datasource:
##    url: jdbc:mysql://192.168.0.54:3306/huashy?useUnicode=true&characterEncoding=utf8&useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=PRC%2B8
#    username: root
#    hikari:
#      jdbc-url: mysql://192.168.0.54:3306/huashy?useUnicode=true&characterEncoding=utf8&useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=PRC%2B8
#
#
#  password: root
#  driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 80